### ISSUE TITLE
Mobisec Justlisten challenge

### ISSUE THREAD

**Issue by mzfr** [abhaynayar/ctf#1]
Hey

I am trying to do the mobisec challenges and I did exactly as you mentioned in the [writeup](https://github.com/abhaynayar/obsidian/blob/master/labs/mobile/mobisec/challs/justlisten.md)

The minimum sdk version is `22` and the target SDK is set to `28`.

Can you please help?

**Comment by abhaynayar** [comment]
Hi,

I never finished doing `justlisten` those were just a few notes I made.

I have ticked the challenges I have done [here](https://github.com/abhaynayar/obsidian/tree/master/labs/mobile/mobisec#challenges).

**Comment by mzfr** [comment]
Oh okay thanks :)
